server:
  port: 8761

eureka:
  instance:
    hostname: www.zzy.com
  client:
    # 声明是否将自己的注册信息注册到eureka服务器，默认true
    register-with-eureka: false   #因为默认情况下一个eureka-server也是一个eureka-client,所以设置注册eureka为false
    # 是否到eureka服务器抓取注册信息，默认true
    fetch-registry: false
    service-url:
      defalutZone: http://www.zzy.com:8761/eureka
  server:
    # 定时器清理注册表的清理间隔，单位毫秒，默认60秒
    eviction-interval-timer-in-ms: 60000
    # 是否开启自我保护模式，默认true
    enable-self-preservation: true